print('='*21)
print('Conversor de Real/Dólar')
print('='*21)
d = float(5.67)
r = float(input('Insira uma quantia em Real: R$'))
print(f'Com a sua quantia em Real, pode se comprar ${r/d:.2f} dólares')
