frase = 'Curso em Vídeo Python'
print(frase[1::2])
print(len(frase),'-Número de caracteres')
print(frase.count('o'))
print(frase.count('o', 0, 13))
print(frase.find('deo'),'-Achar determinado elemento')
print(frase.upper().find('VÍDEO'))
print(frase.find('Android'))
print('Curso' in frase,'-True or False')
print(frase.replace('Python', 'Android'), '-Replace')
print(frase.upper(), '-Tranformação')
print(frase.capitalize())
print(frase.title())
f2 = '   Aprenda Python  '
print(f2)
print(f2.strip(),'-Elimina espaços')
print(f2.rstrip())
print(f2.lstrip())
frase = frase.split()
print(frase, '-Separação de palavras')
print(frase[2])
print(frase[2][1])
print('-'.join(frase))
