nome = str(input('Digite o seu nome: '))
print('Analisando o seu nome...')
nome = nome.strip()
print(f'Seu nome em maiúsculo fica {nome.upper()}')
print(f'Seu nome em minúsculo fica {nome.lower()}')
n = (len(nome) - nome.count(' '))
print(f'Seu nome tem {n} letras')
n1 = nome.find(' ')
print(f'E o seu primeiro nome tem {n1} letras.')
n12 = nome.split()
print(f'E seu primeiro nome é {n12[0]}, e tem {len(n12[0])} letras.')
